/**
 * Sample Dyson improvement plan shown as a blurred preview before unlock.
 */
export const SAMPLE_PLAN_ITEMS = [
  {
    id: "sample-1",
    layer: "crawler_readiness",
    funnel_stage: "awareness" as const,
    issue_type: "crawler_readiness",
    priority: "critical" as const,
    title: "Enable Server-Side Rendering for AI Bots",
    description: "Dyson.com uses client-side JavaScript rendering. AI crawlers like GPTBot and ClaudeBot receive an empty HTML shell with 0 words indexed — preventing any page content, headings, or schema from being read.",
    why_it_matters: "Without SSR, no LLM can read your site content. This single fix could unlock citations across all other dimensions.",
    research_backing: "",
    current_state: "SSR: false — 0 words visible to crawlers",
    desired_state: "All key pages pre-rendered with 500+ words of visible content",
    specific_page: null,
    target_query: null,
    addresses_competitor: null,
    action_steps: "Audit current rendering setup for pages eligible for SSR or SSG\nImplement SSR on homepage, category and product pages\nValidate with curl mimicking GPTBot user-agent\nDeploy and monitor crawl coverage",
    impact: "Could unlock AI citations on all other dimensions",
    effort: "project",
    verification_type: "not_ssr",
    status: "not_started" as const,
    verified_at: null,
    verification_result: {},
  },
  {
    id: "sample-2",
    layer: "entity_strength",
    funnel_stage: "awareness" as const,
    issue_type: "entity_strength",
    priority: "high" as const,
    title: "Strengthen Brand Entity Consistency",
    description: "AI models reference Dyson inconsistently across platforms — sometimes as 'Dyson', 'Dyson Ltd', or 'Dyson Technology'. This entity fragmentation reduces citation confidence and mention frequency.",
    why_it_matters: "Brands with consistent entity descriptions across 4+ platforms are 2.8× more likely to be cited by AI.",
    research_backing: "",
    current_state: "Inconsistent brand descriptions across website, press, and directories",
    desired_state: "Single canonical description used consistently on all platforms",
    specific_page: null,
    target_query: null,
    addresses_competitor: null,
    action_steps: "Write a single canonical 2-sentence brand description\nUpdate website About page, LinkedIn, Wikidata, and Crunchbase to match\nAdd Organization schema with consistent legalName and description fields\nAudit top-10 referring domains for description consistency",
    impact: "Increases AI mention rate by up to 40%",
    effort: "quick_win",
    verification_type: "missing_organization_schema",
    status: "not_started" as const,
    verified_at: null,
    verification_result: {},
  },
  {
    id: "sample-3",
    layer: "content_citability",
    funnel_stage: "consideration" as const,
    issue_type: "content_citability",
    priority: "high" as const,
    title: "Add FAQ Schema to Key Product Pages",
    description: "Product and category pages lack FAQPage JSON-LD schema. AI models heavily rely on FAQ-structured content for direct answer extraction — pages without it are skipped in favour of competitors who have it.",
    why_it_matters: "FAQPage schema is the highest-ROI single schema type for AI citation frequency.",
    research_backing: "",
    current_state: "0 pages with FAQPage or Question schema detected",
    desired_state: "Top 10 product pages each have 4–6 FAQ items in JSON-LD",
    specific_page: null,
    target_query: null,
    addresses_competitor: null,
    action_steps: "Identify the 5 most-asked questions per product category\nWrite direct, 40–80 word answers for each\nImplement FAQPage JSON-LD on product and category pages\nValidate with Google Rich Results Test",
    impact: "Could increase AI citations by 35%",
    effort: "medium",
    verification_type: "missing_schema_faq",
    status: "not_started" as const,
    verified_at: null,
    verification_result: {},
  },
  {
    id: "sample-4",
    layer: "content_freshness",
    funnel_stage: "consideration" as const,
    issue_type: "content_freshness",
    priority: "medium" as const,
    title: "Add Last-Modified Dates to Sitemap",
    description: "The sitemap.xml exists but lacks <lastmod> timestamps. AI crawlers use recency signals to decide which content is authoritative — pages without lastmod are treated as potentially outdated.",
    why_it_matters: "Content freshness signals directly influence AI citation preference when two sources cover the same topic.",
    research_backing: "",
    current_state: "Sitemap has 0 lastmod entries",
    desired_state: "All sitemap entries include accurate lastmod dates",
    specific_page: null,
    target_query: null,
    addresses_competitor: null,
    action_steps: "Update sitemap generator to include <lastmod> for all URLs\nSet lastmod to actual page last-modified date (not publish date)\nResubmit sitemap to Search Console",
    impact: "Improves freshness ranking in AI source selection",
    effort: "quick_win",
    verification_type: "missing_sitemap",
    status: "not_started" as const,
    verified_at: null,
    verification_result: {},
  },
  {
    id: "sample-5",
    layer: "competitive_narrative",
    funnel_stage: "competition" as const,
    issue_type: "competitive_narrative",
    priority: "medium" as const,
    title: "Create Direct Comparison Content vs Shark & Samsung",
    description: "AI models mention Shark and Samsung alongside Dyson in 68% of vacuum cleaner queries but provide no differentiation. Without explicit comparison content, AI defaults to generic category descriptions that don't favour Dyson.",
    why_it_matters: "Brands with explicit competitor comparison pages are 3× more likely to be recommended over competitors in AI responses.",
    research_backing: "",
    current_state: "No comparison pages; AI treats all brands as equivalent alternatives",
    desired_state: "Dedicated comparison landing pages indexed and cited by AI",
    specific_page: null,
    target_query: null,
    addresses_competitor: "Shark, Samsung",
    action_steps: "Create 'Dyson vs Shark' and 'Dyson vs Samsung' comparison pages\nFocus on specific technical differentiators (motor technology, filter efficiency)\nAdd structured data with Product schema and aggregateRating\nBuild internal links from product pages to comparison pages",
    impact: "Could shift AI recommendation rate from 40% to 60%",
    effort: "medium",
    verification_type: "manual",
    status: "not_started" as const,
    verified_at: null,
    verification_result: {},
  },
];
